# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec836b445175e9303100fb4677f0ef4a1f737f8893e840ed0513735bf719255161957a29ba71ada38a1e61372902327d3046f0c60a8005f156d80b649798483f

test:
  secret_key_base: dcb9892e95f02b6da4716f3bfe49afcf8ebc4f7b0bcf005a743a480e3bbe03c87e3d301df68764c8c2cd20e15fe687abf12086a691f5883a0536b191d7537f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
